draft_docs: drafts/
nav:
    - 首页: README.md
    - 校园生活:
          - 开学前准备: campus-life/first-lesson-of-school.md
          - 课程与分数计算: campus-life/different-courses.md
          - 签到考勤: campus-life/class-attendance.md
          - 转专业: campus-life/major-transfer-guide.md
          - 辅修/第二学位: campus-life/minor-or-dual-degree.md
          - 学生邮箱: campus-life/student-email.md
          - 图书馆: campus-life/library.md
          - 化解矛盾: campus-life/resolving-conflicts.md
          - 人际关系: campus-life/social-connections.md
          - 脱单技巧: campus-life/getting-out-of-singleness.md
          - 医保指南: campus-life/medical-insurance.md
          - 国际交流: campus-life/international-exchange.md
          - 圆梦帮扶:
                - 奖助学金申请: campus-life/scholarship.md
                - 勤工俭学申请: campus-life/work-study-program.md
                - 国家助学贷款: campus-life/faq-national-student-loan.md
    - 学术资源:
          - academic-resources/README.md
          - 一些关键概念: academic-resources/some-key-concepts.md
          - 资源:
                - 网络资源获取指南: academic-resources/how-to-get-resources.md
                - 数学: academic-resources/math/learning-resources.md
    - 成长通道: growth-path/README.md
    - 通识技能库:
          - general-skills/README.md
          - 学生优惠: general-skills/student-discounts.md
          - 银行账户与信用卡: general-skills/bank-accounts-and-credit-cards.md
          - 搜索引擎: general-skills/search-platforms.md
          - 工具:
                - 效率软件: general-skills/tools.md
                - 网络安全:
                      #- 双重身份验证: general-skills/cyber security/Authenticator.md
                      - 密码管理: general-skills/password_manage.md
                      - 隐私保护: general-skills/cyber security/privacy.md
                - 奇技淫巧:
                      - 校园跑: general-skills/qi-ji-yin-qiao/campus-running.md
                      - 刷课: general-skills/qi-ji-yin-qiao/pointless-courses.md
          - 学习:
                - 考试和竞赛: general-skills/study/study.md
          - 生活:
                - 生活实用小技巧: general-skills/life-tips.md
                - 保健手段: general-skills/health.md
                - 旅行健康手册: general-skills/health-when-travelling.md
          - 就业:
                - 企业文化: general-skills/recruit-exercitation.md
          - 方法论:
                - 计算机基础技能: general-skills/computer-basic/SurfingTutorial.md
    - 共建社区:
          - community-hub/README.md
          - 关于 Wiki: community-hub/about-wiki.md
    - 博客:
          - blog/index.md

site_name: Ac-Wiki 大学生的百科全书
site_url: https://ac-wiki.org # 正式站点链接
site_description: 属于大学生群体的真·青年大学习
repo_name: Ac-Wiki
repo_url: https://github.com/Ac-Wiki/Ac-Wiki
edit_uri: edit/main/docs/
# copyright:

theme:
    language: zh
    name: material
    font:
        text: Noto Sans
    custom_dir: ./src/overrides
    logo: assets/logo.jpg
    favicon: assets/logo_clear.png
    features:
        - toc.follow # Follow TOC
        - content.action.edit # source edit
        - content.action.view # source view
        - content.tooltips
        - navigation.instant # Instant navigation
        - navigation.instant.progress
        - navigation.top # Top navigation
        - navigation.footer
        - navigation.indexes
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - search.suggest
        - search.highlight
        - search.share
    palette:
        # auto switch between light and dark mode
        - media: "(prefers-color-scheme)"
          toggle:
              icon: material/refresh-auto
              name: 切换到浅色模式
        # match system theme color
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/weather-sunny
              name: 切换到深色模式
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/weather-night
              name: 根据系统主题切换

extra:
    social:
        - icon: simple/qq
          link: https://qm.qq.com/q/WJI3hgBcm4
          name: QQ 群组
        - icon: simple/telegram
          link: https://t.me/AcWiki
          name: Telegram 频道
        - icon: simple/telegram
          link: https://t.me/AcFourm
          name: Telegram 群组
    analytics:
        provider: custom
        feedback:
            title: "本页面对您有帮助吗？"
            ratings:
                - icon: material/thumb-up-outline
                  name: 有帮助
                  data: 1
                  note: >-
                      感谢您的反馈！
                - icon: material/thumb-down-outline
                  name: 有待改进
                  data: 0
                  note: >-
                      请 <a href="https://t.me/AcWiki" target="_blank" rel="noopener">加入频道</a> 或 <a href="https://github.com/Ac-Wiki/Ac-Wiki/issues/new?template=Blank+issue" target="_blank" rel="noopener">发起Issue</a><br>告诉我们如何改进！

extra_css:
    - assets/stylesheets/extra.css

extra_javascript:
    - assets/javascripts/feedback.js
    - https://cn.vercount.one/js
    - assets/javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
    - assets/javascripts/404.js

markdown_extensions:
    - abbr
    - attr_list
    - admonition #强调块
    - footnotes #脚注
    - md_in_html #支持在 html 中使用 markdown 语法
    - toc:
          permalink: true
    - tables
    - pymdownx.details
    - pymdownx.betterem
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.arithmatex:
          generic: true

plugins:
    - search:
          lang: zh
          separator: '[\s\u200b\-]'
          jieba_dict: ./src/overrides/assets/dict.txt
    - git-revision-date-localized: # commit/Modify date
          timezone: Asia/Shanghai
          enable_creation_date: true
          type: timeago
    - git-committers:
          enabled: !ENV [CI, false] # 仅在 CI 环境下启用
          repository: Ac-Wiki/Ac-Wiki
          branch: main
          token: !ENV GITHUB_TOKEN
          exclude_committers:
              - github-actions[bot]
              - actions-user
              - Copilot
              - web-flow
    # - glightbox: # lightbox
    #     touchNavigation: true
    #     loop: true
    #     effect: none
    #     slide_effect: fade
    #     width: auto
    #     height: auto
    #     zoomable: true
    #     draggable: true
    #     skip_classes:
    #       - skip-lightbox
    #     auto_caption: false
    #     caption_position: bottom
    #     background: none
    #     shadow: false
    #     manual: false
    - privacy:
          assets: false # 图片等大量资源托管在 GitHub 上，开启可能会触发 API 请求的限制
    - blog
    - rss:
          match_path: "blog/posts/.*"
          date_from_meta:
              as_creation: date.created
              as_update: date.updated
    - tags
